renderer : mediawiki
input_path : analisi3.tex
output_path : out/out.tex
doc_title: Analisi III
base_path: User:Riccardo Iaconelli
collapse_content_level: 1
collapse_pages_level: 1
create_index: True
export_format: text
export_single_pages: False
export_pages_tree: True
export_book_page: True
print_preparsed_tex: True
lang: it
plugins: [MathCheck]
plugins_configs:
    math_check_online:
        threads: 3
        domain: wikitolearn.org
